export interface IParkInfo {
    name: string;
    state: string;
}

export const PARK_INFOS: IParkInfo[] = [
    { name: "Acadia", state: "Maine" },
    { name: "American Samoa", state: "Samoa" },
    { name: "Arches", state: "Utah" },
    { name: "Badlands", state: "South Dakota" },
    { name: "Big Bend", state: "Texas" },
    { name: "Biscayne", state: "Florida" },
    { name: "Black Canyon of the Gunnison", state: "Colorado" },
    { name: "Bryce Canyon", state: "Utah" },
    { name: "Canyonlands", state: "Utah" },
    { name: "Capitol Reef", state: "Utah" },
    { name: "Carlsbad Caverns", state: "New Mexico" },
    { name: "Channel Islands", state: "California" },
    { name: "Congaree", state: "South Carolina" },
    { name: "Crater Lake", state: "Oregon" },
    { name: "Cuyahoga Valley", state: "Ohio" },
    { name: "Death Valley", state: "California and Nevada" },
    { name: "Denali", state: "Alaska" },
    { name: "Dry Tortugas", state: "Florida" },
    { name: "Everglades", state: "Florida" },
    { name: "Gates of the Arctic", state: "Alaska" },
    { name: "Gateway Arch", state: "Missouri" },
    { name: "Glacier", state: "Montana" },
    { name: "Glacier Bay", state: "Alaska" },
    { name: "Grand Canyon", state: "Arizona" },
    { name: "Grand Teton", state: "Wyoming" },
    { name: "Great Basin", state: "Nevada" },
    { name: "Great Sand Dunes", state: "Colorado" },
    { name: "Great Smoky Mountains", state: "Tennessee" },
    { name: "Guadalupe Mountains", state: "Texas" },
    { name: "Haleakala", state: "Hawaii" },
    { name: "Hawaii Volcanoes", state: "Hawaii" },
    { name: "Hot Springs", state: "Arkansas" },
    { name: "Indiana Dunes", state: "Indiana" },
    { name: "Isle Royale", state: "Michigan" },
    { name: "Joshua Tree", state: "California" },
    { name: "Katmai", state: "Alaska" },
    { name: "Kenai Fjords", state: "Alaska" },
    { name: "Kings Canyon", state: "California" },
    { name: "Kobuk Valley", state: "Alaska" },
    { name: "Lake Clark", state: "Alaska" },
    { name: "Lassen Volcanic", state: "California" },
    { name: "Mammoth Cave", state: "Kentucky" },
    { name: "Mesa Verde", state: "Colorado" },
    { name: "Mount Rainier", state: "Washington" },
    { name: "New River Gorge", state: "West Virginia" },
    { name: "North Cascades", state: "Washington" },
    { name: "Olympic", state: "Washington" },
    { name: "Petrified Forest", state: "Arizona" },
    { name: "Pinnacles", state: "California" },
    { name: "Redwood", state: "California" },
    { name: "Rocky Mountain", state: "Colorado" },
    { name: "Saguaro", state: "Arizona" },
    { name: "Sequoia", state: "California" },
    { name: "Shenandoah", state: "Virginia" },
    { name: "Theodore Roosevelt", state: "North Dakota" },
    { name: "Virgin Islands", state: "Virgin Islands" },
    { name: "Voyageurs", state: "Minnesota" },
    { name: "White Sands", state: "New Mexico" },
    { name: "Wind Cave", state: "South Dakota" },
    { name: "Wrangell-St. Elias", state: "Alaska" },
    { name: "Yellowstone", state: "Wyoming" },
    { name: "Yosemite", state: "California" },
    { name: "Zion", state: "Utah" },
];
